"""Add files to task relationship

Revision ID: 4a0dcca8b2fb
Revises: c9e880f10259
Create Date: 2021-09-05 14:39:03.006859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0dcca8b2fb'
down_revision = 'c9e880f10259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'task_id')
    # ### end Alembic commands ###
