"""users table

Revision ID: 5875c10dae58
Revises: 
Create Date: 2021-01-05 15:52:02.000416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5875c10dae58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('tasks', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task', sa.TEXT(), nullable=True))
    op.drop_column('tasks', 'text')
    # ### end Alembic commands ###
