name: Generate a build and push to build branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build # The build command of your project

      - name: Copy files to deploy
        working-directory: .
        run: |
          mkdir deploy
          cp -r ./app ./deploy
          cp ./server.py ./deploy
          cp ./cron.py ./deploy
          cp ./config.py ./deploy
          cp ./requirements.txt ./deploy
          cp ./.env.template ./deploy
          cp ./README.md ./deploy

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: deploy # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
